### ISSUE TITLE
OR cant detect underwater

### ISSUE THREAD

**Issue by GBRPlus** [llde/TESReloaded10#103]
OR cant detect underwater because sky proceed is canceled by this:
SafeWriteJump(0x00542F63, 0x00542FC1); // Avoids to remove the sun over the scene when underwater

298556d49c1fb6f2ae4773f59b9e16877533d987

**Comment by GBRPlus** [comment]
Tes->sky->GetIsUnderWater() is useless

**Comment by llde** [comment]
MAybe I can use that hook to better detect when underwater.

**Comment by GBRPlus** [comment]
Maybe, good idea.

**Comment by llde** [comment]
fixed by 0a5628f0f55b721f986ee165bc1f3ac70a140beb
