### ISSUE TITLE
allow config retrocompatibility

### ISSUE THREAD

**Issue by mchaptel** [llde/TESReloaded10#61]
Fix crashes when config changes by offering default values that can be pulled when one is missing

**Comment by llde** [comment]
The entire configuration system needs to be rewritten

**Comment by mchaptel** [comment]
Agreed, I have created a milestone for new menu + config system and added it to the Trello

**Comment by llde** [comment]
As for commit 3fd9ea7dab3efa059336e0baef4f5043ffe529ec,  TESR provide a new configuration system that offer partial backward  compatibilty to option, and a more sane format of configruution TOML.  Thanks to Serde and Rust
